config/routes.rb
Sakuhinten::Application.routes.draw do

  get "welcome/index"
  resources :comments

  root :to => "kumos#index"

  resources :comments, :only => ['create']
  resources :maes
  resources :atos
  resources :kumos, :only => ['index','new', 'create', 'edit', 'update']

  

end

app/models/ato.rb
class Ato < ActiveRecord::Base
  mount_uploader :image, ShashinUploader
  belongs_to :kumo
end

app/controllers/atos_controller.rb
class AtosController < ApplicationController
  before_action :set_ato, only: [:show, :edit, :update, :destroy]

  # GET /atos
  # GET /atos.json
  def index
    @atos = Ato.all
  end

  # GET /atos/1
  # GET /atos/1.json
  def show
  end

  # GET /atos/new
  def new
    @ato = Ato.new
  end

  # GET /atos/1/edit
  def edit
  end

  # POST /atos
  # POST /atos.json
  def create
    @ato = Ato.new(ato_params)

    respond_to do |format|
      if @ato.save
        format.html { redirect_to @ato, notice: 'Ato was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ato }
      else
        format.html { render action: 'new' }
        format.json { render json: @ato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atos/1
  # PATCH/PUT /atos/1.json
  def update
    respond_to do |format|
      if @ato.update(ato_params)
        format.html { redirect_to @ato, notice: 'Ato was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atos/1
  # DELETE /atos/1.json
  def destroy
    @ato.destroy
    respond_to do |format|
      format.html { redirect_to atos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ato
      @ato = Ato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ato_params
      params.require(:ato).permit(:image, :kumo_id)
    end
end

app/helpers/atos_helper.rb
module AtosHelper
end

app/views/atos/_form.html.erb
<%= form_for(@ato) do |f| %>
  <% if @ato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ato.errors.count, "error") %> prohibited this ato from being saved:</h2>

      <ul>
      <% @ato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :kumo_id %><br>
    <%= f.number_field :kumo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atos/edit.html.erb
<h1>Editing ato</h1>

<%= render 'form' %>

<%= link_to 'Show', @ato %> |
<%= link_to 'Back', atos_path %>

app/views/atos/index.html.erb
<h1>Listing atos</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Kumo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @atos.each do |ato| %>
      <tr>
        <td><%= ato.image %></td>
        <td><%= ato.kumo_id %></td>
        <td><%= link_to 'Show', ato %></td>
        <td><%= link_to 'Edit', edit_ato_path(ato) %></td>
        <td><%= link_to 'Destroy', ato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ato', new_ato_path %>

app/views/atos/new.html.erb
<h1>New ato</h1>

<%= render 'form' %>

<%= link_to 'Back', atos_path %>

app/views/atos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @ato.image %>
</p>

<p>
  <strong>Kumo:</strong>
  <%= @ato.kumo_id %>
</p>

<%= link_to 'Edit', edit_ato_path(@ato) %> |
<%= link_to 'Back', atos_path %>