config/routes.rb
Sakuhinten::Application.routes.draw do

  get "welcome/index"
  resources :comments

  root :to => "kumos#index"

  resources :comments, :only => ['create']
  resources :maes
  resources :atos
  resources :kumos, :only => ['index','new', 'create', 'edit', 'update']

  

end

app/models/kumo.rb
class Kumo < ActiveRecord::Base
  has_one :ato, :dependent => :destroy
  has_one :mae, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :ato
  accepts_nested_attributes_for :mae
end

app/controllers/kumos_controller.rb
class KumosController < ApplicationController
  before_action :set_kumo, only: [:show, :edit, :update, :destroy, :confirm]

  # GET /kumos
  # GET /kumos.json
  def index
    @kumos = Kumo.includes([:ato, :mae, :comments]).references([:atos, :maes, :comments])
  end

  # GET /kumos/1
  # GET /kumos/1.json
  def show
  end

  # GET /kumos/new
  def new
    @kumo = Kumo.new
    @kumo.build_mae
    @kumo.build_ato
  end

  # GET /kumos/1/edit
  def edit
  	if @kumo.answer != params[:answer]
  	  redirect_to root_path, :notice => 'あなたの回答が間違っているようです。'
  	end
  end
  
  def confirm
  end

  # POST /kumos
  # POST /kumos.json
  def create
    @kumo = Kumo.new(kumo_params)

    respond_to do |format|
      if @kumo.save
        format.html { redirect_to kumos_path, notice: 'Kumo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @kumo }
      else
        format.html { render action: 'new' }
        format.json { render json: @kumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kumos/1
  # PATCH/PUT /kumos/1.json
  def update
    respond_to do |format|
      if @kumo.update(kumo_params)
        format.html { redirect_to kumos_path, notice: 'Kumo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @kumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kumos/1
  # DELETE /kumos/1.json
  def destroy
    @kumo.destroy
    respond_to do |format|
      format.html { redirect_to kumos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kumo
      @kumo = Kumo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kumo_params
      params.require(:kumo).permit(:user_id, :title, :name, :question, :answer, :mae_attributes => [:id, :image], :ato_attributes => [:id, :image])
    end    
end

app/helpers/kumos_helper.rb
module KumosHelper
end

app/views/kumos/_form.html.erb
<div class="row">
	<%= form_for(@kumo) do |f| %>
		<div class="col-sm-6 col-md-6 col-lg-6">
			<div class="well">
				<%= f.label :title, "タイトル" %><br>
				<%= f.text_field :title, :class=>'form-control input-lg', :placeholder => "タイトル" %>
			</div>
			<div class="well">
				<%= f.fields_for :mae, :html => {:multipart => true}  do |mae_field| %>
					<div class="field">
						<%= mae_field.label :image, "ビフォー(変わる前の写真を投稿してください)"%>
						<%= mae_field.file_field :image %>
					</div>
				<% end %>
			</div>
		
			<div class="well">
				<%= f.fields_for :ato, :html => {:multipart => true}  do |ato_field| %>
					<div class="field">
						<%= ato_field.label :image, "アフター(変わった後の写真を投稿してください)" %>
						<%= ato_field.file_field :image %>
					</div>
				<% end %>
			</div>
		</div>
		<div class="col-sm-6 col-md-6 col-lg-6">
			<div class="well">
				<%= f.label :name, "名前" %><br>
				<%= f.text_field :name, :class=>'form-control', :placeholder => "名前" %>
				<br>
				<%= f.label :name, "秘密の質問(編集するときに必要です)" %><br>
				<%= f.text_field :question, :class=>'form-control', :placeholder => "秘密の質問" %>
				<%= f.label :name, "秘密の質問の答え" %><br>
				<%= f.text_field :answer, :class=>'form-control', :placeholder => "秘密の質問の答え" %>
			</div>

			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<%= f.submit "登録・更新する", :class=>'btn btn-primary btn-lg' %>　<%= link_to '戻る', kumos_path, :class=>'btn btn-danger btn-lg' %>
			</div>
		</div>
	<% end %>
</div>

app/views/kumos/_kumo.html.erb
<% iro = rand(5) %>
<% if iro == 0 %>
<% iro = "panel-info" %>
<% elsif iro == 2 %>
<% iro = "panel-info" %>
<% elsif iro == 3 %>
<% iro = "panel-info" %>
<% else %>
<% iro = "panel-info" %>
<% end %>
<div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
	<div class="panel <%= iro %>">
		<div class="panel-heading" style="text-align:center;">
			<p><%= kumo.name %>さんの作品</p>
		</div>
		<div class="panel-body zoomTarget" data-targetsize="0.8" data-closeclick="true">
			<div class="ba_box">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<%= image_tag kumo.mae.image_url.to_s, :class => 'img-thumbnail', :width => '200px' %>
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<%= image_tag kumo.ato.image_url.to_s, :class => 'img-thumbnail', :width => '200px' %>
					</div>
				</div>
				<div class=" col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<h3><%= kumo.title %></h3>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<button id="open<%= kumo.id %>" class="btn">コメント一覧</button><button id="close<%= kumo.id %>" class="btn hidden_btn">閉じる</button>　<button id="edit<%= kumo.id %>" class="btn btn-success">編集する</button>
			<div class="hidden_box" id="editform<%= kumo.id %>">
			<h4>秘密の質問の答えを入力してください。</h4>
			<%= kumo.question %>
			<%= form_tag(edit_kumo_path(kumo), :method => :get, :class=>'form-inline' ) do %>
				<%= text_field_tag :answer %>
				<%= submit_tag '編集ページヘ', :class=>'btn btn-info'%>
			<% end %>
			</div>
			<div class="hidden_box" id="hidden<%= kumo.id %>">
				<hr>
				<button id="fbutton<%= kumo.id %>" class="btn btn-info hidden_btn">コメントする</button>
				<div class="hidden_box" id="form<%= kumo.id %>">
				あなたはどのタイプ？
				<% @comment = kumo.comments.build %>
					<%= form_for @comment, :class=>'form-inline' do |f| %>
						<div class="form-group">
							<div class="radio">
								<label>
									<%= f.radio_button :jinkaku, 1, :required => true %> <p class="text-warning">いいところを褒めまくる天使タイプ</p>
								</label>
							</div>
							<div class="radio">
								<label>
									<%= f.radio_button :jinkaku, 2, :required => true %> <p class="text-danger">弱点を見つけて攻める悪魔タイプ</p>
								</label>
							</div>
							<div class="radio">
								<label>
									<%= f.radio_button :jinkaku, 3, :required => true %> <p class="text-info">似たものを探してくる情報屋タイプ</p>
								</label>
							</div>
							<div class="radio">
								<label>
									<%= f.radio_button :jinkaku, 4, :required => true %> <p class="text-success">賢明な助言をする仙人タイプ</p>
								</label>
							</div>
						</div>
						<div class="form-group">
							<%= f.text_field :name, :class=>'form-control input-lg', :placeholder => "名前", :required => true %>
						</div>
						<div class="form-group">
							<%= f.text_area :content, :class=>'form-control input-lg', :rows => '2',  :placeholder => "コメント", :required => true %>
						</div>
							<%= f.hidden_field :kumo_id %>
						<div class="action">
							<%= f.submit "コメントする", :class=>'btn btn-primary'%>
						</div>
					<% end %>
				</div>
				<hr>
				<div>
				<% kumo.comments.each do |comment|%>
					<div>
						<% if comment.jinkaku == 1 %>
						<p class="text-warning"><strong><%= comment.content %></strong><br><small>by天使：<%= comment.name %></small></p>
						<% elsif comment.jinkaku == 2 %>
						<p class="text-danger"><strong><%= comment.content %></strong><br><small>by悪魔：<%= comment.name %></small></p>
						<% elsif comment.jinkaku == 3 %>
						<p class="text-info"><strong><%= comment.content %></strong><br><small>by情報屋：<%= comment.name %></small></p>
						<% elsif comment.jinkaku == 4 %>
						<p class="text-success"><strong><%= comment.content %></strong><br><small>by仙人：<%= comment.name %></small></p>
						<% end %>
					</div>
				<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<%= javascript_tag do %>
	$(function(){
		$("#open<%= kumo.id %>").on('click',function(){
			$("#hidden<%= kumo.id %>").toggle("fast");
			$("#open<%= kumo.id %>").hide();
			$("#close<%= kumo.id %>").show();
			$("#form<%= kumo.id %>").hide();
			$("#fbutton<%= kumo.id %>").show();
			$("#editform<%= kumo.id %>").hide();			
		});
		$("#close<%= kumo.id %>").on('click',function(){
			$("#hidden<%= kumo.id %>").toggle("fast");
			$("#open<%= kumo.id %>").show();
			$("#close<%= kumo.id %>").hide();
			$("#editform<%= kumo.id %>").hide();
		});
		$("#fbutton<%= kumo.id %>").on('click',function(){
			$("#form<%= kumo.id %>").toggle("fast");
			$("#fbutton<%= kumo.id %>").hide();
		});
		$("#edit<%= kumo.id %>").on('click',function(){
			$("#editform<%= kumo.id %>").toggle("fast");
		});
	});
<% end %>

app/views/kumos/edit.html.erb
<h3>ビフォーアフターを編集する</h3>

<%= render 'form' %>

app/views/kumos/index.html.erb
<h3>世界を変えるビフォーアフター</h3>
<div class="row">
	<%= render @kumos %>
</div>

<br/>
<%= link_to '新しく作成する', new_kumo_path, :class=>'btn btn-info btn-lg' %>

app/views/kumos/new.html.erb
<h3>新しいビフォーアフターを作成する</h3>

<%= render 'form' %>

app/views/kumos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @kumo.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @kumo.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @kumo.name %>
</p>

<%= link_to 'Edit', edit_kumo_path(@kumo) %> |
<%= link_to 'Back', kumos_path %>