config/routes.rb
Sakuhinten::Application.routes.draw do

  get "welcome/index"
  resources :comments

  root :to => "kumos#index"

  resources :comments, :only => ['create']
  resources :maes
  resources :atos
  resources :kumos, :only => ['index','new', 'create', 'edit', 'update']

  

end

app/models/mae.rb
class Mae < ActiveRecord::Base
  mount_uploader :image, ShashinUploader
  belongs_to :kumo
end

app/controllers/maes_controller.rb
class MaesController < ApplicationController
  before_action :set_mae, only: [:show, :edit, :update, :destroy]

  # GET /maes
  # GET /maes.json
  def index
    @maes = Mae.all
  end

  # GET /maes/1
  # GET /maes/1.json
  def show
  end

  # GET /maes/new
  def new
    @mae = Mae.new
  end

  # GET /maes/1/edit
  def edit
  end

  # POST /maes
  # POST /maes.json
  def create
    @mae = Mae.new(mae_params)

    respond_to do |format|
      if @mae.save
        format.html { redirect_to @mae, notice: 'Mae was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mae }
      else
        format.html { render action: 'new' }
        format.json { render json: @mae.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maes/1
  # PATCH/PUT /maes/1.json
  def update
    respond_to do |format|
      if @mae.update(mae_params)
        format.html { redirect_to @mae, notice: 'Mae was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mae.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maes/1
  # DELETE /maes/1.json
  def destroy
    @mae.destroy
    respond_to do |format|
      format.html { redirect_to maes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mae
      @mae = Mae.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mae_params
      params.require(:mae).permit(:image, :kumo_id)
    end
end

app/helpers/maes_helper.rb
module MaesHelper
end

app/views/maes/_form.html.erb
<%= form_for(@mae) do |f| %>
  <% if @mae.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mae.errors.count, "error") %> prohibited this mae from being saved:</h2>

      <ul>
      <% @mae.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :kumo_id %><br>
    <%= f.number_field :kumo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maes/edit.html.erb
<h1>Editing mae</h1>

<%= render 'form' %>

<%= link_to 'Show', @mae %> |
<%= link_to 'Back', maes_path %>

app/views/maes/index.html.erb
<h1>Listing maes</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Kumo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @maes.each do |mae| %>
      <tr>
        <td><%= mae.image %></td>
        <td><%= mae.kumo_id %></td>
        <td><%= link_to 'Show', mae %></td>
        <td><%= link_to 'Edit', edit_mae_path(mae) %></td>
        <td><%= link_to 'Destroy', mae, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mae', new_mae_path %>

app/views/maes/new.html.erb
<h1>New mae</h1>

<%= render 'form' %>

<%= link_to 'Back', maes_path %>

app/views/maes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @mae.image %>
</p>

<p>
  <strong>Kumo:</strong>
  <%= @mae.kumo_id %>
</p>

<%= link_to 'Edit', edit_mae_path(@mae) %> |
<%= link_to 'Back', maes_path %>